epochs: 5
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 2 # 32

tensorboard_dir: "runs/experiment_1"
checkpoint_dir: "checkpoints/experiment_1"
save_every_n_epochs: 10
resume_from_checkpoint: null  